### ISSUE TITLE
rumi will only fail if the last command fails

### ISSUE THREAD

**Issue by hwmrocker** [trivago/rumi#35]
I have this rumi file and even if the tests are failing I get a build successful.

```
stages:
    test 2.7:
      docker:
        www:
          image: python:2.7
          volumes:
            - ".:/app"
      commands:
        - pip install --upgrade /app
        - pip install pytest
        - python -c "h='='*80;n='';print('\n'.join([h,n,'Tests for Python 2.7',n,h]))"
        - py.test /app/tests
        - python -c "h='='*80;n='';print('\n'.join([h,n,'Tests for Python 2.7 - Done',n,h]))"
```
